/**
 * Flashcard Model
 * 
 * Stores AI-generated flashcard sets created from uploaded PDF documents.
 * Generated by Groq (Llama 3.3 70B) with 8 cards per set.
 * Supports three difficulty levels for adaptive learning.
 * 
 * Relationships:
 *   - userId → User who requested the flashcards
 *   - documentId → Source PDF document
 */
import mongoose from "mongoose";

const flashcardSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    documentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Document",
      required: true,             // The PDF document these cards were generated from
    },
    difficulty: {
      type: String,
      enum: ["beginner", "intermediate", "advanced"],  // Controls language complexity in AI prompt
      required: true,
    },
    cards: [
      {
        front: { type: String, required: true },   // Question or term
        back: { type: String, required: true },     // Answer or definition
      },
    ],
    topic: {
      type: String,
      default: "",               // Auto-populated with the document title
    },
  },
  { timestamps: true }
);

const Flashcard = mongoose.model("Flashcard", flashcardSchema);
export default Flashcard;

