/**
 * Questions Model
 * 
 * Represents a single multiple-choice question within a Quiz.
 * Generated by Google Gemini AI with exactly 4 options per question.
 * Each question includes the correct answer and an explanation.
 * 
 * Relationships:
 *   - quizId → Parent Quiz this question belongs to
 */

import mongoose from "mongoose";

const questionSchema = new mongoose.Schema({
    quizId:{
        type: mongoose.Schema.Types.ObjectId,
        ref: "Quiz",
        required: true             // Every question must belong to a quiz
    },
    content:{
        type: String,
        required: true             // The question text
    },
    options: [
        {
            type: String,          // Exactly 4 answer options (enforced by AI prompt)
        }
    ],
    correctOption:{
        type: String,              // The correct answer string (matches one of the options)
    },
    explanation:{
        type: String               // AI-generated explanation of why the answer is correct
    }
}, { timestamps: true })

// Created and exported the Questions model
export const Questions = mongoose.model("Questions", questionSchema);
